FROM golang:1.21

WORKDIR /notifier

COPY go.* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o /docker-bn-rest-migrator ./cmd/migrator

CMD [ "/docker-bn-rest-migrator" ]
