env: "local"
postgres_con: "postgres://postgres:123@localhost:5432/users?sslmode=disable"
app_secret: "aba123"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
clients:
  sso:
    address: "localhost:44044"
    timeout: 4s
    retries: 10
